services:
  social-graphql-api:
    container_name: social-graphql-api
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: graphql
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  graphql-pgadmin:
    container_name: graphql-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
